export const STATES_IN_INDIA = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const popularCitiesOrDistricts = {
  "Andaman and Nicobar Islands": ["Port Blair", "Havelock Island", "Neil Island", "Diglipur", "Mayabunder", "Rangat"],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Tirupati",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kakinada",
    "Rajahmundry",
    "Anantapur",
    "Kadapa",
    "Eluru",
    "Ongole",
    "Vizianagaram",
    "Srikakulam",
    "Machilipatnam"
  ],
  "Arunachal Pradesh": ["Itanagar", "Tawang", "Naharlagun", "Pasighat", "Bomdila", "Ziro", "Tezu", "Roing", "Aalo", "Namsai"],
  "Assam": [
    "Guwahati",
    "Jorhat",
    "Dibrugarh",
    "Silchar",
    "Tezpur",
    "Nagaon",
    "Tinsukia",
    "Sivasagar",
    "Diphu",
    "North Lakhimpur",
    "Karimganj",
    "Goalpara",
    "Bongaigaon",
    "Dhubri",
    "Haflong"
  ],
  "Bihar": [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Arrah",
    "Bihar Sharif",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chhapra",
    "Saharsa",
    "Sasaram",
    "Hajipur"
  ],
  "Chandigarh": ["Chandigarh"],
  "Chhattisgarh": [
    "Raipur",
    "Bilaspur",
    "Bhilai",
    "Korba",
    "Rajnandgaon",
    "Raigarh",
    "Jagdalpur",
    "Ambikapur",
    "Dhamtari",
    "Chirmiri",
    "Mahasamund",
    "Durg",
    "Kanker",
    "Kawardha",
    "Kondagaon"
  ],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Silvassa", "Diu", "Amli", "Naroli", "Vapi"],
  "Delhi": [
    "New Delhi",
    "Old Delhi",
    "Connaught Place",
    "Dwarka",
    "Rohini",
    "Pitampura",
    "Janakpuri",
    "Laxmi Nagar",
    "Shahdara",
    "Karol Bagh",
    "Chandni Chowk",
    "Saket",
    "Vasant Kunj",
    "Greater Kailash",
    "Mayur Vihar"
  ],
  "Goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Calangute",
    "Candolim",
    "Anjuna",
    "Baga",
    "Colva",
    "Vagator",
    "Morjim",
    "Arambol",
    "Benaulim",
    "Porvorim"
  ],
  "Gujarat": [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Nadiad",
    "Mehsana",
    "Morbi",
    "Surendranagar",
    "Bharuch",
    "Vapi",
    "Navsari",
    "Veraval",
    "Porbandar",
    "Godhra",
    "Palanpur"
  ],
  "Haryana": [
    "Chandigarh",
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Sirsa",
    "Bahadurgarh",
    "Jind"
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Manali",
    "Kullu",
    "Dharamshala",
    "Mandi",
    "Solan",
    "Palampur",
    "Kasauli",
    "Dalhousie",
    "Chamba",
    "Hamirpur",
    "Una",
    "Bilaspur",
    "Nahan",
    "Kangra"
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Udhampur",
    "Kathua",
    "Sopore",
    "Kupwara",
    "Pulwama",
    "Poonch",
    "Rajouri",
    "Budgam",
    "Ganderbal",
    "Bandipore",
    "Kulgam"
  ],
  "Jharkhand": [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Deoghar",
    "Giridih",
    "Ramgarh",
    "Phusro",
    "Medininagar",
    "Chirkunda",
    "Gumla",
    "Dumka",
    "Chaibasa",
    "Sahibganj"
  ],
  "Karnataka": [
    "Bengaluru",
    "Mysuru",
    "Hubballi",
    "Mangaluru",
    "Belagavi",
    "Ballari",
    "Vijayapura",
    "Kalaburagi",
    "Shivamogga",
    "Tumakuru",
    "Davanagere",
    "Raichur",
    "Hassan",
    "Udupi",
    "Dharwad"
  ],
  "Kerala": [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Kannur",
    "Kottayam",
    "Malappuram",
    "Kasaragod",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Perinthalmanna"
  ],
  "Ladakh": ["Leh", "Kargil", "Diskit", "Zanskar", "Nubra", "Khaltse"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Amini", "Andrott", "Minicoy", "Kalpeni"],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena"
  ],
  "Maharashtra": [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Navi Mumbai",
    "Kolhapur",
    "Kalyan-Dombivli",
    "Vasai-Virar",
    "Bhiwandi",
    "Mira-Bhayandar",
    "Panvel",
    "Dombivli",
    "Ulhasnagar",
    "Bhusawal",
    "Malegaon",
    "Ahmednagar",
    "Akola",
    "Alibag",
    "Bhandara",
    "Beed",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Latur",
    "Nanded",
    "Osmanabad",
    "Parbhani",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Wardha",
    "Washim",
    "Yavatmal",
    "Ambernath",
    "Ichalkaranji",
    "Pimpri-Chinchwad",
    "Khopoli",
    "Baramati",
    "Lonavala",
    "Shirdi",
    "Ambajogai",
    "Khed",
    "Chiplun",
    "Karad",
    "Parli",
    "Udgir",
    "Malkapur",
    "Shegaon",
    "Pusad",
    "Karjat",
    "Sangamner",
    "Manmad",
    "Pathardi",
    "Sillod",
    "Wai",
    "Palghar",
    "Virar",
    "Nalasopara",
    "Pen",
    "Uran",
    "Khandala",
    "Mahad",
    "Pandharpur",
    "Kopargaon",
    "Shrirampur",
    "Deolali",
    "Bhandardara",
    "Alibaug",
    "Murud",
    "Dahanu",
    "Kalyan"
  ],
  "Manipur": ["Imphal", "Thoubal", "Kakching", "Ukhrul", "Churachandpur", "Bishnupur", "Senapati", "Tamenglong"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin", "Williamnagar", "Baghmara", "Resubelpara", "Mairang"],
  "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Kolasib", "Serchhip", "Lawngtlai", "Mamit"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha", "Zunheboto", "Mon", "Phek"],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Puri",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Balangir",
    "Rayagada",
    "Paradip",
    "Dhenkanal"
  ],
  "Puducherry": ["Puducherry", "Auroville", "Karaikal", "Mahe", "Yanam", "Villianur"],
  "Punjab": [
    "Chandigarh",
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Pathankot",
    "Hoshiarpur",
    "Batala",
    "Moga",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar"
  ],
  "Rajasthan": [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Sri Ganganagar",
    "Pali",
    "Bharatpur",
    "Jhunjhunu",
    "Kishangarh",
    "Chittorgarh"
  ],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Rangpo", "Singtam", "Jorethang", "Ravangla"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukkudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur"
  ],
  "Telangana": [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ramagundam",
    "Mahbubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Siddipet",
    "Kolhapur",
    "Bodhan",
    "Jagtial"
  ],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar", "Belonia", "Ambassa", "Khowai", "Teliamura"],
  "Uttar Pradesh": [
    "Lucknow",
    "Agra",
    "Varanasi",
    "Kanpur",
    "Prayagraj",
    "Ghaziabad",
    "Meerut",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Noida",
    "Firozabad",
    "Jhansi"
  ],
  "Uttarakhand": [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Haldwani",
    "Roorkee",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Pithoragarh",
    "Ramnagar",
    "Mussoorie",
    "Almora",
    "Pauri",
    "Kotdwar",
    "Tehri"
  ],
  "West Bengal": [
    "Kolkata",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Kharagpur",
    "Malda",
    "Krishnanagar",
    "Baharampur",
    "Barrackpore",
    "Haldia",
    "Jalpaiguri",
    "Shantipur",
    "Medinipur"
  ]
};
